from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch

def create_pdf_report(
    portfolio_tickers,
    benchmark_ticker,
    start_date,
    end_date,
    initial_investment,
    final_portfolio_value,
    inverse_final_value,
    final_benchmark_value,
    portfolio_total_return,
    inverse_total_return,
    benchmark_total_return,
    portfolio_annual_return,
    inverse_annual_return,
    benchmark_annual_return,
    portfolio_volatility,
    inverse_volatility,
    benchmark_volatility,
    portfolio_sharpe,
    inverse_sharpe,
    benchmark_sharpe,
    portfolio_drawdown,
    inverse_drawdown,
    benchmark_drawdown,
    portfolio_beta,
    inverse_beta,
    inverse_weights
):

    doc = SimpleDocTemplate("../data/Portfolio_Report.pdf")

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            "Historical Portfolio Backtester",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 24))

    story.append(
        Paragraph(
            "This report was automatically generated by the Historical Portfolio Backtester.",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Portfolio Information</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            f"<b>Portfolio:</b> {', '.join(portfolio_tickers)}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Benchmark:</b> {benchmark_ticker}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Initial Investment:</b> ${initial_investment:,.2f}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Period:</b> {start_date} to {end_date}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "<b>Performance Summary</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 12))

    table_data = [
        ["Metric", "Equal Weight", "Inverse Variance", benchmark_ticker],

        ["Final Value",
        f"${final_portfolio_value:,.2f}",
        f"${inverse_final_value:,.2f}",
        f"${final_benchmark_value:,.2f}"],

        ["Total Return",
        f"{portfolio_total_return:.2f}%",
        f"{inverse_total_return:.2f}%",
        f"{benchmark_total_return:.2f}%"],

        ["Annual Return",
        f"{portfolio_annual_return:.2f}%",
        f"{inverse_annual_return:.2f}%",
        f"{benchmark_annual_return:.2f}%"],

        ["Volatility",
        f"{portfolio_volatility:.2f}%",
        f"{inverse_volatility:.2f}%",
        f"{benchmark_volatility:.2f}%"],

        ["Sharpe Ratio",
        f"{portfolio_sharpe:.2f}",
        f"{inverse_sharpe:.2f}",
        f"{benchmark_sharpe:.2f}"],

        ["Max Drawdown",
        f"{portfolio_drawdown:.2f}%",
        f"{inverse_drawdown:.2f}%",
        f"{benchmark_drawdown:.2f}%"],

        ["Beta",
        f"{portfolio_beta:.2f}",
        f"{inverse_beta:.2f}",
        "1.00"]
    ]

    table = Table(table_data)

    table.hAlign = "CENTER"

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
        ])
    )

    story.append(table)

    story.append(PageBreak())

    story.append(
        Paragraph(
            "<b>Portfolio Performance Chart</b>",
            styles["Heading2"]
        )
    )
    
    story.append(Spacer(1, 12))

    chart = Image("../data/portfolio_comparison.png")

    chart.drawWidth = 7.2 * inch
    chart.drawHeight = 4.8 * inch

    story.append(chart)

    story.append(Spacer(1, 5))

    story.append(
        Paragraph(
            "Figure 1. Historical performance comparison between the Equal Weight Portfolio, Inverse Variance Portfolio, and the selected benchmark.",
            styles["Italic"]
        )
    )

    story.append(Spacer(1, 24))

    story.append(
        Paragraph(
            "<b>Inverse Variance Portfolio Weights</b>",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 12))

    weights_data = [
    ["Ticker", "Weight (%)"]
    ]

    for ticker, weight in zip(portfolio_tickers, inverse_weights):
        weights_data.append(
            [
                ticker,
                f"{weight * 100:.2f}%"
            ]
        )

    weights_table = Table(weights_data)

    weights_table.hAlign = "CENTER"

    weights_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
        ])
    )

    story.append(weights_table)

    story.append(PageBreak())

    story.append(
        Paragraph(
            "<b>Conclusion</b>",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 18))

    story.append(
        Paragraph(
            f"""
            The Equal Weight portfolio achieved a final value of
            <b>${final_portfolio_value:,.2f}</b>,
            while the Inverse Variance portfolio finished with
            <b>${inverse_final_value:,.2f}</b>.
            """,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            f"""
            Compared with the selected benchmark ({benchmark_ticker}),
            both portfolio strategies demonstrated different
            risk-return characteristics over the investment period.
            """,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            f"""
            The Equal Weight portfolio produced an annualized return of
            <b>{portfolio_annual_return:.2f}%</b>,
            while the Inverse Variance portfolio produced
            <b>{inverse_annual_return:.2f}%</b>.
            """,
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            f"""
            The Inverse Variance strategy reduced portfolio volatility
            to <b>{inverse_volatility:.2f}%</b>,
            demonstrating how alternative weighting methods can help
            balance investment risk while maintaining competitive
            long-term returns.
            """,
            styles["BodyText"]
        )
    )

    doc.build(story)